# Use root/mysql as user/password credentials

version: '3.8'

services:
  python_apis:
    build:
      context: ./
      dockerfile: Dockerfile
    image: prueba-web-mel
    command: gunicorn entrypoint:app --bind 0.0.0.0:5000
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    hostname: web
  
  vue:
    build:
      context: ./
      dockerfile: DockerfileVue
    image: vueapp:Mel
    container_name: "vue_app_container"
    ports:
      - "7000:8080"
  # frontend:
  #   build:
  #     context: ./
  #     dockerfile: DockerfileVue
  #   #image: node:16-alpine
  #   working_dir: /src
  #   volumes:
  #     - ./app/:/usr/src/
  #   ports:
  #     - 7000:80
  #   command: npx vite --host

  bases_de_datos:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bw1L[{wezRx9
      MYSQL_DATABASE: webtofly_asegurarse
      MYSQL_USER: webtofly_db_user
      MYSQL_PASSWORD: bw1L[{wezRx9
    ports:
      - 4306:3306
      - 43060:33060
    volumes:
      - ./data/db:/var/lib/mysql

  adminer:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=bases_de_datos
    hostname: adminer

# volumes:
#   db_volume:
#   pgadmin-data:
